### ISSUE TITLE
v2 Checklist

### ISSUE THREAD

**Issue by polarathene** [polarathene/biglobby#5]
Tasks that need to be completed before we release v2:
- [ ] Finish supporting duplicate characters so that calls to CriminalsManager that interact with the criminals table do not break.
- [x] Improve the dynamic colour generator by switching to a colour space like HSL/HUSL. The Hue value will make it easy to avoid the yellow/orange ranges where the contours are visual indications of player state which leads to confusion.
- [x] Better indication of lobby size or type on Crime.net. Display `([current_players] / [lobby_size])` or person icon + `x[current_players]` text.
- [x] Ensure that maps can be completed. Aftershock, Mountain, Framing Frame(Day 2 in train), etc seem to have issues or limitations on completing an event/objective. In larger lobby sizes this will also affect other trigger areas like escape zones, these conditions should consider using a min player count instead of all, or <=4 for events that check vehicle seats are filled. 

Seamlessly switch between regular and big lobbies(not essential for v2):
- [x] A visual indication or label or filter option to differentiate between regular/big lobbies.
- [x] See if we can display/join regular lobbies without having to disable pdmod & BLT mod. This should also enable achievements/stats/etc when in regular lobbies.
- [x] Hosting at a lobby size of 4 should work as a regular lobby as if the mod was disabled. Not required but helps towards seamless lobby type switching.
